### ISSUE TITLE
Improved communication of CG activity

### ISSUE THREAD

**Issue by ianbjacobs** [w3c/cg-council#7]
@dontcallmedom and others have recently improved our ability to understand CG activities levels (both on CG home pages and in the dashboard [1]). After discussion with Dom today we are interested in further improvements.

Assumption:

* We have a measure of "hotness" for each CG, for example as the dashboard [1] currently does. 

Proposals:

1. Sort the list of CGs [2] by hotness. This should be the default sort order.

2. On each CG home page, present relevant hotness information, such as:
    - [ ]   Publication activity (e.g., new publications or titles of recent or active pull requests)
    - [ ]   Recent hot topics (e.g., from GitHub or email)
    - [ ]   Where most of the activity of this group is happening (e.g., when a group has multiple GitHub repos)
    - [ ]   Rank of this CG in the "hotness" list ("Ranked #3 most active CG"...with a link to the full list).
    - [ ]   Number of people who have joined the group in the past 2 months
    - [ ]   Names of organizations with 3 or more participants in the group
    - [x]  Email/GitHub/Wiki activity (as was recently added to CG home pages)

   Note: If this information is useful to participants and non-participants alike, then it could go at the top of the
   CG pages.

3. Automate the process of culling inactive CGs. We already have a manual process for culling CGs that involves looking at "hotness", whether the group has a chair, and so forth. 

Benefits:

* Makes it easier for the community to understand which groups are active, and what topics are active.
* Culling will reduce the noise. Automation will reduce the burden on staff. 

Observation:

* Although the CG dashboard [1] is useful, I think we should integrate its most useful features directly into CG pages (the list of groups and each group's home page). If we do the dashboard may still have value, but I am guessing primarily to the staff. 

[1] https://w3c.github.io/cg-monitor/
[2] https://www.w3.org/community/groups/

**Comment by ianbjacobs** [comment]
Additional ideas here:

* Enable tagging of groups in the list of groups (e.g., "Internationalization") to allow people to track a set of groups.

**Comment by ianbjacobs** [comment]
Idea:

* Help increase activity of groups (and chances of success) with more support (e.g., improved documentation, polling Team for ideas) for people to get started and run a group.

**Comment by dontcallmedom** [comment]
https://www.w3.org/community/groups/ is now sorted by level of activity by default (suggestion number 1 in this issue)

**Comment by ianbjacobs** [comment]
Cool, thank you!!
